//
//  OSCTCPClient Notification.swift
//  OSCKit • https://github.com/orchetect/OSCKit
//  © 2020-2025 Steffan Andrews • Licensed under MIT License
//

#if !os(watchOS)

extension OSCTCPClient {
    /// A notification event generated by the TCP client.
    public enum Notification {
        case connected(remoteHost: String, remotePort: UInt16)
        case disconnected(remoteHost: String, remotePort: UInt16)
        // case connectionTimeout(remoteHost: String, remotePort: UInt16)
    }
}

extension OSCTCPClient.Notification: Equatable { }
    
extension OSCTCPClient.Notification: Hashable { }
    
extension OSCTCPClient.Notification: Sendable { }

#endif
