//
//  OSCTCPClient Notification.swift
//  OSCKit • https://github.com/orchetect/OSCKit
//  © 2020-2025 Steffan Andrews • Licensed under MIT License
//

#if !os(watchOS)

@preconcurrency import CocoaAsyncSocket

extension OSCTCPClient {
    /// A notification event generated by the TCP client.
    public enum Notification {
        case connected
        case disconnected(error: GCDAsyncSocketError?)
    }
}

extension OSCTCPClient.Notification: Equatable { }
    
extension OSCTCPClient.Notification: Hashable { }
    
extension OSCTCPClient.Notification: Sendable { }

#endif
