version: 1
builder:
  configs:
  - platform: macosSpm
    scheme: OSCKit-CI
  - platform: macosXcodebuild
    scheme: OSCKit-CI
  - platform: iOS
    scheme: OSCKit-CI
  - platform: tvOS
    scheme: OSCKit-CI
  - platform: watchOS
    scheme: OSCKit-CI
  - platform: visionOS
    scheme: OSCKit-CI
external_links:
  documentation: "https://orchetect.github.io/OSCKit/"
