//
//  OSCTCPNotificationHandlerBlock.swift
//  OSCKit • https://github.com/orchetect/OSCKit
//  © 2020-2025 Steffan Andrews • Licensed under MIT License
//

/// A notification event handler for notifications generated by OSCKit TCP classes.
public typealias OSCTCPNotificationHandlerBlock = (OSCTCPNotification) -> Void


