//
//  OSCTCPNotification.swift
//  OSCKit • https://github.com/orchetect/OSCKit
//  © 2020-2025 Steffan Andrews • Licensed under MIT License
//

/// A notification event generated by OSCKit TCP classes.
public enum OSCTCPNotification {
    case connected(remoteHost: String, remotePort: UInt16)
    case disconnected(remoteHost: String, remotePort: UInt16)
    // case connectionTimeout(remoteHost: String, remotePort: UInt16)
}

extension OSCTCPNotification: Equatable { }

extension OSCTCPNotification: Hashable { }

extension OSCTCPNotification: Sendable { }
