//
//  OSCTCPServer Notification.swift
//  OSCKit • https://github.com/orchetect/OSCKit
//  © 2020-2025 Steffan Andrews • Licensed under MIT License
//

#if !os(watchOS)

extension OSCTCPServer {
    /// A notification event generated by the TCP server.
    public enum Notification {
        case connected(remoteHost: String, remotePort: UInt16, clientID: OSCTCPClientSessionID)
        case disconnected(remoteHost: String, remotePort: UInt16, clientID: OSCTCPClientSessionID)
    }
}

extension OSCTCPServer.Notification: Equatable { }
    
extension OSCTCPServer.Notification: Hashable { }
    
extension OSCTCPServer.Notification: Sendable { }

#endif
