//
//  OSCTCPServer Notification.swift
//  OSCKit • https://github.com/orchetect/OSCKit
//  © 2020-2026 Steffan Andrews • Licensed under MIT License
//

#if !os(watchOS)

extension OSCTCPServer {
    /// A notification event generated by the TCP server.
    public enum Notification {
        /// The server accepted a connection from a remote client.
        case connected(remoteHost: String, remotePort: UInt16, clientID: OSCTCPClientSessionID)
        
        /// The server was notified that a remote client connection has closed.
        /// If the disconnection was a result of an error, the error will be non-nil.
        case disconnected(remoteHost: String, remotePort: UInt16, clientID: OSCTCPClientSessionID, error: (any Error)?)
    }
}

extension OSCTCPServer.Notification: Equatable {
    public static func == (lhs: Self, rhs: Self) -> Bool {
        switch (lhs, rhs) {
        case let (.connected(leftHost, leftPort, leftClientID), .connected(rightHost, rightPort, rightClientID)):
            // if all variables the same then true (notifications are equal), else false
            return (leftHost == rightHost) && (leftPort == rightPort) && (leftClientID == rightClientID)
        case let (
            .disconnected(leftHost, leftPort, leftClientID, leftError),
            .disconnected(rightHost, rightPort, rightClientID, rightError)
        ):
            // all variables (except error) must be the same to continue, else false
            guard (leftHost == rightHost), leftPort == rightPort, leftClientID == rightClientID else { return false }
            // check if errors are the same
            switch (leftError, rightError) {
            // if both nil, then true
            case (nil, nil): return true
            // if one nil, one error, then false
            case (nil, _), (_, nil): return false
            // if localizedDescription is the same then true
            case let (left?, right?): return left.localizedDescription == right.localizedDescription
            }
        default:
            return false
        }
    }
}

extension OSCTCPServer.Notification: Hashable {
    public func hash(into hasher: inout Hasher) {
        switch self {
        case let .connected(host, port, id):
            // combine 0 to distinguish from .disconnected
            hasher.combine(0)
            // combine variables for unique hash
            hasher.combine(host)
            hasher.combine(port)
            hasher.combine(id)
        case let .disconnected(host, port, id, err):
            // combine 1 to distinguish from .connected
            hasher.combine(1)
            // combine variables for unique hash
            hasher.combine(host)
            hasher.combine(port)
            hasher.combine(id)
            hasher.combine(err?.localizedDescription)
        }
    }
}
    
extension OSCTCPServer.Notification: Sendable { }

#endif
