//
//  OSCTCPServer Notification.swift
//  OSCKit • https://github.com/orchetect/OSCKit
//  © 2020-2025 Steffan Andrews • Licensed under MIT License
//

#if !os(watchOS)

@preconcurrency import CocoaAsyncSocket

extension OSCTCPServer {
    /// A notification event generated by the TCP server.
    public enum Notification {
        /// The server accepted a connection from a remote client.
        case connected(remoteHost: String, remotePort: UInt16, clientID: OSCTCPClientSessionID)
        
        /// The server was notified that a remote client connection has closed.
        /// If the disconnection was a result of an error, the error will be non-nil.
        case disconnected(remoteHost: String, remotePort: UInt16, clientID: OSCTCPClientSessionID, error: GCDAsyncSocketError?)
    }
}

extension OSCTCPServer.Notification: Equatable { }
    
extension OSCTCPServer.Notification: Hashable { }
    
extension OSCTCPServer.Notification: Sendable { }

#endif
